-- Replaces the earlier placeholder menu items with the REAL menus from photos.
-- Safe to run once. Deletes old items per kitchen first, then inserts real ones.

-- ============ DELETE OLD PLACEHOLDER ITEMS ============
delete from menu_items where kitchen_id = (select id from kitchens where slug = 'shiros');
delete from menu_items where kitchen_id = (select id from kitchens where slug = 'dope-truck');
delete from menu_items where kitchen_id = (select id from kitchens where slug = 'midori-bean');
delete from menu_items where kitchen_id = (select id from kitchens where slug = 'tokyo-toki');

-- ============ SHIRO'S  (mapped from the "BIT" burger menu) ============
insert into menu_items (kitchen_id, name, description, price, category, is_veg) values
  ((select id from kitchens where slug='shiros'), 'Salted Fries', null, 130, 'fries', true),
  ((select id from kitchens where slug='shiros'), 'Peri Peri Fries', null, 140, 'fries', true),
  ((select id from kitchens where slug='shiros'), 'Veg Loaded Fries', null, 170, 'fries', true),
  ((select id from kitchens where slug='shiros'), 'Paneer & Fries', null, 170, 'fries', true),
  ((select id from kitchens where slug='shiros'), 'Chicken Loaded Fries', null, 200, 'fries', false),
  ((select id from kitchens where slug='shiros'), 'Chicken Katsu & Fries', null, 220, 'fries', false),
  ((select id from kitchens where slug='shiros'), 'Onion Rings', null, 150, 'sides', true),
  ((select id from kitchens where slug='shiros'), 'Veg Cheese Nuggets (6pcs)', null, 150, 'sides', true),
  ((select id from kitchens where slug='shiros'), 'Chicken Popcorn', null, 170, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Chicken Cheese Nuggets (6pcs)', null, 170, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Classic Wings', null, 180, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Crispy Wings (6pcs)', null, 200, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Chicken Tenders (6pcs)', null, 220, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Devil''s Spicy Tenders (6pcs)', null, 250, 'sides', false),
  ((select id from kitchens where slug='shiros'), 'Veggie & Cheese Sando', 'Fresh veggies & cheese layered with lettuce, tomato, and signature sauce, toasted bread.', 130, 'sando', true),
  ((select id from kitchens where slug='shiros'), 'Paneer Sando', 'Crispy paneer patty layered with lettuce, tomato, cheese and signature jam, toasted bread.', 160, 'sando', true),
  ((select id from kitchens where slug='shiros'), 'Grilled Chicken Sando', 'Grilled chicken patty layered with lettuce, tomato, cheese, signature jam, toasted bread.', 160, 'sando', false),
  ((select id from kitchens where slug='shiros'), 'Katsu Chicken Sando', 'Crispy chicken katsu layered with lettuce, cheese and signature jam, toasted bread.', 190, 'sando', false),
  ((select id from kitchens where slug='shiros'), 'Bit''s Hara-Bhara', 'Minty potato patty, tomato, lettuce, base sauce, honey mustard.', 100, 'burgers', true),
  ((select id from kitchens where slug='shiros'), 'Bit''s Paneer', 'Crispy paneer patty, peri peri, base sauce, cucumber mayo mix.', 140, 'burgers', true),
  ((select id from kitchens where slug='shiros'), 'Veg Juicy Lucy', 'Veggie patty filled with melted cheese, jalapeño, lettuce, base sauce, tomato, honey mustard.', 150, 'burgers', true),
  ((select id from kitchens where slug='shiros'), 'Veg Double Doubles', 'Crispy potato + paneer patty, double cheese, cucumber mayo, tomato, lettuce, honey mustard.', 180, 'burgers', true),
  ((select id from kitchens where slug='shiros'), 'Veg Devil Spicy', 'Crispy spicy paneer, jalapeño, ghost pepper, spicy tomato jam, lettuce, base sauce.', 200, 'burgers', true),
  ((select id from kitchens where slug='shiros'), 'Bit''s Classic', 'Grilled chicken patty, cheese, caramelized onions, tomato, lettuce, base sauce, honey mustard.', 150, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Spicy Grilled', 'Grilled chicken patty, spicy tomato jam, cheese, caramelized onion, tomato, lettuce, honey mustard.', 165, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Crispy AF', 'Crispy chicken thigh, lettuce, jalapeño, honey mustard, base sauce.', 180, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Juicy Lucy', 'Chicken patty filled with melted cheese, jalapeño, lettuce, base sauce, honey mustard.', 180, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Devil''s Spicy Burger', 'Crispy chicken thigh, jalapeño, hot pepper, spicy tomato jam, lettuce, base sauce.', 250, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Double Doubles', 'Two juicy chicken patties, double cheese, caramelized onions, jalapeño, base sauce, honey mustard.', 250, 'burgers', false),
  ((select id from kitchens where slug='shiros'), 'Mutton Juicy Lucy', 'Mutton patty filled with melted cheese, jalapeño, lettuce, base sauce, honey mustard.', 280, 'burgers', false);

-- ============ THE DOPE TRUCK ============
insert into menu_items (kitchen_id, name, description, price, category, is_veg) values
  ((select id from kitchens where slug='dope-truck'), 'Margherita', 'Tomato pelati, buffalo mozzarella, basil.', 349, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Capri Bianco', 'Creamy white bianco sauce, garlic butter, cheese.', 349, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Garden House', 'Roasted bell peppers, broccoli, zucchini, black olives, mozzarella, olive oil.', 349, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Pesto Burrata (chef''s special)', 'Fresh burrata cheese on homemade pesto sauce, charred mushrooms on the side.', 479, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Mushroom Truffle', 'Charred mushrooms, caramelised onions, tomato pelati, mushroom & truffle oil on top.', 369, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Quattro Formaggi', 'Mozzarella, cheddar, Amul, Parmesan on top with fried basil.', 399, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Exotic Veggies', '70gms protein. All exotic vegetables, power of protein.', 449, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Paneer & Broccoli', '80gms protein. Paneer chunks, loads of broccoli, mozzarella.', 469, 'pizza', true),
  ((select id from kitchens where slug='dope-truck'), 'Chicken Loaded', '90gms protein. Chicken chunks, chicken pepperoni, mozzarella.', 499, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Mutton Keema Loaded', '95gms protein. Mutton keema on top with mozzarella.', 519, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Smoked BBQ Chicken', 'Smokey BBQ chicken, jalapeños, raw onions, buffalo mozzarella.', 419, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Pepperoni Piccante', 'Chicken pepperoni, jalapeños, olives, bell peppers, onions, mozzarella.', 419, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Chicken Tikka', 'Roasted chicken chunks, bell peppers, paprika, olive oil, mozzarella.', 419, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Chicken Seekh Kebab Heaven', 'Roasted chicken seekh kebab chunks, raw onions, paprika slice, mozzarella.', 449, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Mutton Seekh Kebab Heaven', 'Juicy mutton seekh kebab on top, raw onions, paprika slices, mozzarella.', 479, 'pizza', false),
  ((select id from kitchens where slug='dope-truck'), 'Cheese Chilli Garlic Bread', 'Freshly baked in the oven.', 229, 'garlic bread', true),
  ((select id from kitchens where slug='dope-truck'), 'Four Cheese Garlic Bread w Chilli Oil', 'Mozzarella, cheddar, Amul, Parmesan, fried basil.', 249, 'garlic bread', true),
  ((select id from kitchens where slug='dope-truck'), 'Dope Tandoori Momos (6pcs)', 'Choose Achari/Afghani/Piri-Piri/Haryali.', 239, 'tandoori', true),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Chicken Wings (8pcs)', 'Choose Achari/Afghani/Piri-Piri/Haryali.', 299, 'tandoori', false),
  ((select id from kitchens where slug='dope-truck'), 'Peanut Masala Eggs (3pcs)', 'Roasted eggs wrapped in Indian masala, topped with peanuts and butter.', 179, 'tandoori', false),
  ((select id from kitchens where slug='dope-truck'), 'Stuffed Soya Chaap', 'Roasted soya chunks with roasted peanuts and butter.', 279, 'tandoori', true),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Stuffed Mushrooms', 'Masala mushroom tikka.', 279, 'tandoori', true),
  ((select id from kitchens where slug='dope-truck'), 'Mushroom Galouti Kebabs', 'Mouth-melting mushroom kebabs, shallow fried in desi ghee.', 299, 'tandoori', true),
  ((select id from kitchens where slug='dope-truck'), 'Falafel Pita W Hummus', 'House-made falafel served w freshly baked pita bread.', 299, 'tandoori', true),
  ((select id from kitchens where slug='dope-truck'), 'Bhatti Da Murgh (700-800gms)', 'Whole baby chicken left overnight in ground spices, charred in tandoor, served with hummus & mint relish.', 499, 'tandoori', false),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Paneer Tikka', 'Charred paneer chunks with mint relish & salad.', 399, 'small plates', true),
  ((select id from kitchens where slug='dope-truck'), 'Haryali Paneer or Chicken Tikka', 'Marinated in in-house Haryali marinade, served with mint relish & salad.', 399, 'small plates', true),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Chicken Tikka (small plate)', 'Charred chicken chunks topped with mint relish & salad.', 399, 'small plates', false),
  ((select id from kitchens where slug='dope-truck'), 'Adana Chicken Seekh Kebab', 'Juicy Turkish kebabs made with minced boneless chicken and charred in tandoor.', 399, 'small plates', false),
  ((select id from kitchens where slug='dope-truck'), 'Adana Mutton Seekh Kebab', 'Juicy Turkish kebabs made with minced boneless mutton, placed on a crispy butter naan.', 449, 'small plates', false),
  ((select id from kitchens where slug='dope-truck'), 'Turkish Falafel Shawarma', 'Crunchy falafel stuffed in freshly baked bread w tzitziki, hummus w pickled salad.', 299, 'shawarma', true),
  ((select id from kitchens where slug='dope-truck'), 'Smoked Soya Shawarma', 'Roasted soya chunks stuffed in freshly baked bread with tzitziki and hummus.', 249, 'shawarma', true),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Paneer & Onion Shawarma', 'Butter roasted paneer tikka, wrapped in freshly baked bread with hummus and mint relish.', 299, 'shawarma', true),
  ((select id from kitchens where slug='dope-truck'), 'Tandoori Chicken & Onion Shawarma', 'Butter roasted chicken tikka wrapped in freshly baked bread with hummus and mint relish.', 299, 'shawarma', false),
  ((select id from kitchens where slug='dope-truck'), 'Chicken Seekh Kebab Shawarma', 'Juicy chicken Adana kebab wrapped in freshly baked bread with hummus & tzitziki.', 329, 'shawarma', false),
  ((select id from kitchens where slug='dope-truck'), 'Mutton Seekh Kebab Shawarma', 'Juicy mutton Adana kebab wrapped in freshly baked bread with hummus & tzitziki.', 379, 'shawarma', false);

-- ============ MIDORI BEAN ============
insert into menu_items (kitchen_id, name, description, price, category, is_veg) values
  ((select id from kitchens where slug='midori-bean'), 'Espresso', null, 80, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Doppio', null, 110, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Americano', null, 160, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Cappuccino', null, 180, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Cafe Latte', null, 200, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Cafe Mocha', null, 200, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Cortado', null, 200, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Affogato', null, 180, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Flat White', null, 180, 'hot espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'White Choco Latte', null, 220, 'midori special', true),
  ((select id from kitchens where slug='midori-bean'), 'Nutella Fluffy Coffee', null, 220, 'midori special', true),
  ((select id from kitchens where slug='midori-bean'), 'Mont Blanc', null, 240, 'midori special', true),
  ((select id from kitchens where slug='midori-bean'), 'Coconut Cappuccino', null, 220, 'midori special', true),
  ((select id from kitchens where slug='midori-bean'), 'Marshmallow Hot Chocolate', null, 210, 'hot chocolate', true),
  ((select id from kitchens where slug='midori-bean'), 'French Hot Chocolate', null, 230, 'hot chocolate', true),
  ((select id from kitchens where slug='midori-bean'), 'Classic Frappe', null, 180, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Vietnamese Iced Latte', null, 250, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Salted Caramel Coffee', null, 250, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Oreo Cold Coffee', null, 250, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Cinnamon Mocha', null, 250, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Americano', 'Orange / Coconut / Lemon Honey.', 180, 'cold espresso', true),
  ((select id from kitchens where slug='midori-bean'), 'Masala Chai', null, 40, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Green Tea', null, 50, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Honey Lemon Ginger Tea', null, 90, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Peach Iced Tea', null, 180, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Lemon Mint Iced Tea', null, 180, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Mango Iced Tea', null, 190, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Masala Diet Coke', null, 110, 'tea', true),
  ((select id from kitchens where slug='midori-bean'), 'Biscoff Shake', null, 250, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'The KitKat Shake', null, 250, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Fudgy Brownie Shake', null, 250, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Rose & Cardamom Shake', null, 220, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Strawberry Shake', null, 230, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Oreo Vanilla Shake', null, 250, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Mango Brownie Shake', null, 250, 'shakes', true),
  ((select id from kitchens where slug='midori-bean'), 'Lemon Mint Mojito', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Watermelon Mojito', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Green Apple Mojito', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Orange Lime Mojito', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Inspiring Summer', null, 200, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Piña Colada', null, 200, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Peach & Curry Leaves', null, 200, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Jamun Punch', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Kaccha Aam', null, 180, 'mocktails', true),
  ((select id from kitchens where slug='midori-bean'), 'Hot Matcha Latte', null, 280, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Hot Coconut Matcha', null, 300, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Matcha Latte', null, 300, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Strawberry Matcha', null, 320, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Blueberry Matcha', null, 320, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Iced Mango Matcha', null, 320, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Cloud Coconut Matcha', null, 320, 'matcha', true),
  ((select id from kitchens where slug='midori-bean'), 'Maple & Butter Pancakes', null, 200, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Nutella Chocolate Pancakes', null, 250, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Blueberry & Cream Pancakes', null, 250, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Biscoff Crunch Pancakes', null, 250, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Brownie Pie', null, 230, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Brownie W Vanilla', null, 210, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Lemon Cheesecake', null, 230, 'desserts', true),
  ((select id from kitchens where slug='midori-bean'), 'Peanut Butter Banana Smoothie', null, 220, 'smoothies', true),
  ((select id from kitchens where slug='midori-bean'), 'Kiwi Smoothie', null, 240, 'smoothies', true),
  ((select id from kitchens where slug='midori-bean'), 'Blueberry Smoothie', null, 240, 'smoothies', true),
  ((select id from kitchens where slug='midori-bean'), 'High-Protein Smoothie', '38 grams protein.', 340, 'smoothies', true);

-- ============ TOKYO TOKI ============
insert into menu_items (kitchen_id, name, description, price, category, is_veg) values
  ((select id from kitchens where slug='tokyo-toki'), 'Manchow Soup (Veg)', 'Choice of veg or chicken.', 149, 'soups', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Manchow Soup (Chicken)', 'Choice of veg or chicken.', 179, 'soups', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Sweet Corn Soup (Veg)', null, 149, 'soups', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Sweet Corn Soup (Chicken)', null, 179, 'soups', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Hot & Sour Soup (Veg)', null, 149, 'soups', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Hot & Sour Soup (Chicken)', null, 179, 'soups', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Lung Fung Soup (Veg)', null, 179, 'soups', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Lung Fung Soup (Chicken)', null, 199, 'soups', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Thai Tom Yum Soup (Veg)', null, 179, 'soups', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Thai Tom Yum Soup (Chicken)', null, 199, 'soups', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Classic Fried Rice (Veg)', null, 219, 'noodles & rice', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Classic Fried Rice (Chicken)', null, 249, 'noodles & rice', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Burnt Garlic Fried Rice (Veg)', null, 229, 'noodles & rice', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Burnt Garlic Fried Rice (Chicken)', null, 259, 'noodles & rice', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Hakka Noodle (Veg)', null, 279, 'noodles & rice', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Hakka Noodle (Chicken)', null, 299, 'noodles & rice', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Chilli Garlic Noodle (Veg)', null, 299, 'noodles & rice', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Chilli Garlic Noodle (Chicken)', null, 319, 'noodles & rice', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Pad Thai (Veg)', null, 379, 'noodles & rice', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Pad Thai (Chicken)', null, 399, 'noodles & rice', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Japanese Katsu Curry', 'Crispy breaded chicken in Japanese curry with short-grain rice.', 479, 'bowls & curry', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Chicken Krapow Curry', 'Ground chicken, lemon leaf, fried egg on top, jasmine rice & holy basil.', 499, 'bowls & curry', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Red or Green Thai Curry (Veg)', null, 449, 'bowls & curry', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Red or Green Thai Curry (Chicken)', null, 479, 'bowls & curry', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Park Street Sweet Chilli Potato', 'It''s a classic!', 219, 'starters', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Dragon Spring Roll', 'Sesame veggie roll with sweet chilli sauce.', 229, 'starters', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Shroom Sambal', 'Crispy mushrooms in chilli sambal sauce.', 299, 'starters', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Oyster Basil Cottage Cheese', 'Cottage cheese chunks in oyster sauce with fresh basil.', 379, 'starters', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Korean Chicken Wings', 'Smokey apple sauce & feta sour cream.', 299, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Shapta Chicken', 'Grilled chicken chunks in garlic oyster.', 379, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Kung Pao Chicken/Cottage Cheese', 'Sichuan stir fried diced protein, cashews, dried chilli.', 399, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Chilli Paneer or Chicken', 'All time favourite.', 379, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Dynamite Spicy Prawns', 'Crispy fried prawns tossed in our house-made signature dynamite sauce.', 649, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Three Pepper Bomb Prawns', 'Crispy prawns wok-tossed in a bold blend of three kinds of pepper.', 649, 'starters', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Glass Noodle Salad', 'Glass noodles, kaffir lime, bell peppers & crushed peanuts.', 249, 'salad', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Korean Kimchi Salad', 'Gochujang with purple cabbage.', 249, 'salad', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Honey Flat Noodles', 'Crispy fried noodles with honey glaze, garnished with an ice cream scoop.', 179, 'sweet-tooth', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Thai Asparagus & Edamame Dimsum (5pcs)', 'Crunchy asparagus, kaffir lime, cilantro & edamame beans.', 339, 'dimsum', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Wild Mushroom & Cream Cheese Dimsum (5pcs)', 'Water chestnut, cream cheese, mushrooms & chilli oil.', 379, 'dimsum', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Classic Soya Momo (6pcs)', 'Soya, cabbage, carrot, spring onion.', 209, 'dimsum', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Chicken Chilli Oil Dimsum (5pcs)', 'Scallion, cilantro, ponzu in starch paper.', 299, 'dimsum', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Old School Chicken Momo (6pcs)', 'Steamed or pan-fried.', 239, 'dimsum', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Juicy Mutton Momo/Kothey (6pcs)', 'House-made momos stuffed with boneless mutton, finely chopped onions.', 319, 'dimsum', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Green Avocado Maki (8pcs)', 'Avocado, takuan, green apple, pickled cucumber, caramelised onions.', 479, 'sushi', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Asparagus California Roll', 'Cucumber, asparagus, carrot pickle, sesame seed, bell peppers.', 479, 'sushi', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Katsu Chicken Roll', 'Crispy chicken, avocado, cucumber, cream cheese, sesame & mayo.', 499, 'sushi', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Teriyaki Chicken & Avocado Roll', 'Teriyaki glazed chicken, smashed avocado, cucumber, spicy mayo.', 499, 'sushi', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Tiger California Shrimp Roll', 'Tiger prawn tempura, avocado, English cucumber & Japanese mayo.', 579, 'sushi', false),
  ((select id from kitchens where slug='tokyo-toki'), 'Braised Tofu Ramen', 'Braised tofu, beans, sprouts, bok choy, jalapeño pepper & cilantro.', 479, 'ramen', true),
  ((select id from kitchens where slug='tokyo-toki'), 'Spicy Chicken Ramen', 'Topped with grilled chicken, seasonal grains, bamboo shoots & spring onion.', 499, 'ramen', false);